name: Actualizar Datos ETH

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

# Jobs a ejecutar
jobs:
  actualizar_datos:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 2. Configurar Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Ejecutar script de recolección de datos Collector
        run: |
          python src/proyecto/static/models/collector.py

      - name: 5. Listar archivos y directorios
        run: ls -lR

      - name: 6. Commit y subir cambios
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add src/proyecto/static/data/historical.db src/proyecto/static/data/historical.csv src/proyecto/static/models/collector.log
          git commit -m "Actualizar datos económicos" || echo "No hay cambios para commitear"
          git push origin main
